import { CompanyT, OpinionCardT } from "./types"
import { UserT } from "./types"
import { CredentialT, RecentlySeenT } from "./types"

export const suggestion4Testing: OpinionCardT[] = [
	{
		user_name: "name of the user",
		body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem culpa optio animi deleniti ipsum dolorum voluptatem vel iste saepe ad sed maiores cupiditate, debitis nihil atque facilis minus! Alias, voluptatum.",
		type: true,
		id: 1,
		rating: 0,
	},
]

export const rating4Testing: OpinionCardT[] = [
	{
		user_name: "name of the user",
		body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem culpa optio animi deleniti ipsum dolorum voluptatem vel iste saepe ad sed maiores cupiditate, debitis nihil atque facilis minus! Alias, voluptatum.",
		type: false,
		id: 2,
		rating: 7,
	},
]

export const user4Testing: UserT = {
	name: "Gonzalo",
	email: "email_1@gmail.com",
	recovery_email: "email_2@gmail.com",
	phone_number: "+54 011 1234-5678",
	slots_available: 2,
	role: "semi-premium",
	id: 100,
	anti_fishing_secret: "@Leonard1618",
	invitation_code: "AJFV8S67B4JSA8",
	security_access_code: "AJF682JK9S",
	preferred_lang: "en",
}

export const secretKey4Testing = "DCRMALCXPEZOFKZH"

export const credential4Testing: CredentialT[] = [
	{
		id: 1,
		user_id: 1,
		company_id: null,
		company: null,
		company_name: "test",
		description: "roses are red, violets are blue, lorem ipsum this is a description",
		last_seen: "2021-02-15 17:32:23",
		recently_seen: "",
		user_name: "example name",
		char_count: 12,
		email: {
			opening: "fa",
			char_count: 7,
			ending: "@gmail.com",
			email: "fake_mail@gmail.com",
		},
		password: {
			char_count: 9,
			password: "123456789",
		},
		username: {
			char_count: 12,
			username: "xXUserNameXx",
		},
		phone_number: {
			opening: "+54",
			char_count: 7,
			ending: "31",
			phone_number: "+54-011-5555-5531",
		},
		security_question_answer: {
			security_question: "what is the meaning of life?",
			security_answer: "42",
		},
		security_code: {
			unique_code: "D7WK29JDU8",
			unique_code_length: 10,
			multiple_codes: "codigo-1 codigo-2 codigo-2",
			multiple_codes_length: 11,
			crypto_codes:
				"Lorem ipsum dolor sit amet consectetur adipisicing elit Eaque odio accusamus cumque nemo veniam? Perferendis consequatur incidunt fugiat delectus reiciendis atque Ipsam excepturi molestiae quasi ratione id veniam pariatur laborum",
			crypto_codes_length: 30,
		},
		created_at: "2021-02-15 17:32:23",
		updated_at: "2021-02-15 17:32:23",
	},
	{
		id: 2,
		user_id: 1,
		company_id: 3,
		company_name: "test 2",
		company: {
			id: 3,
			name: "test 2",
			url_logo:
				"https://i.pinimg.com/originals/20/be/24/20be24eb7d0ef02c2b227d2b6f172e0d.jpg",
		},
		description: "I know the last description didn't rhyme",
		last_seen: "2021-02-15 17:32:23",
		recently_seen: true,
		user_name: null,
		char_count: null,
		email: {
			opening: "fa",
			char_count: 7,
			ending: "@gmail.com",
			email: "fake_mail@gmail.com",
		},
		password: {
			char_count: 9,
			password: "123456789",
		},
		username: {
			char_count: 12,
			username: "xXUserNameXx",
		},
		phone_number: {
			opening: "+54",
			char_count: 7,
			ending: "31",
			phone_number: "+54-011-5555-5531",
		},
		security_question_answer: {
			security_question: "what is the meaning of life?",
			security_answer: "42",
		},
		security_code: {
			unique_code: "D7WK29JDU8",
			unique_code_length: 10,
			multiple_codes: null,
			multiple_codes_length: 0,
			crypto_codes:
				"Lorem ipsum dolor sit amet consectetur adipisicing elit Eaque odio accusamus cumque nemo veniam? Perferendis consequatur incidunt fugiat delectus reiciendis atque Ipsam excepturi molestiae quasi ratione id veniam pariatur laborum",
			crypto_codes_length: 30,
		},
		created_at: "2021-02-15 17:32:23",
		updated_at: "2021-02-15 17:32:23",
	},
	{
		id: 3,
		user_id: 1,
		company_id: 5,
		company_name: "test 3",
		company: null,
		last_seen: "2021-02-15 17:32:23",
		recently_seen: true,
		user_name: "example name 2",
		char_count: 14,
		email: {
			opening: "fa",
			char_count: 7,
			ending: "@gmail.com",
			email: "fake_mail@gmail.com",
		},
		password: {
			char_count: 9,
			password: "123456789",
		},
		username: {
			char_count: 12,
			username: "xXUserNameXx",
		},
		phone_number: {
			opening: "+54",
			char_count: 7,
			ending: "31",
			phone_number: "+54-011-5555-5531",
		},
		security_question_answer: {
			security_question: "what is the meaning of life?",
			security_answer: "42",
		},
		security_code: {
			unique_code: "D7WK29JDU8",
			unique_code_length: 10,
			multiple_codes:
				" D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 D7WK29JDU8 ",
			multiple_codes_length: 11,
			crypto_codes:
				"Lorem ipsum dolor sit amet consectetur adipisicing elit Eaque odio accusamus cumque nemo veniam? Perferendis consequatur incidunt fugiat delectus reiciendis atque Ipsam excepturi molestiae quasi ratione id veniam pariatur laborum",
			crypto_codes_length: 30,
		},
		created_at: "2021-02-15 17:32:23",
		updated_at: "2021-02-15 17:32:23",
	},
]

export const recentlySeen4Testing: RecentlySeenT[] = [
	{
		company_name: "test 1",
		last_seen: "2021-02-23 17:32:23",
		id: 1,
		created_at: "2021-02-15 17:32:23",
		updated_at: "2021-02-15 17:32:23",
		accessing_device: "Macintosh; Intel Mac OS X 11_2_3",
		accessing_platform: "web",
	},
]

export const companies4Testing: CompanyT[] = [
	{ name: "The Shawshank Redemption", id: 1, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Godfather", id: 2, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Godfather: Part II", id: 3, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Dark Knight", id: 4, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "12 Angry Men", id: 5, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Schindler's List", id: 6, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Pulp Fiction", id: 7, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "The Lord of the Rings: The Return of the King",
		id: 8,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{
		name: "The Good, the Bad and the Ugly",
		id: 9,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "Fight Club", id: 10, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "The Lord of the Rings: The Fellowship of the Ring",
		id: 11,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{
		name: "Star Wars: Episode V - The Empire Strikes Back",
		id: 12,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "Forrest Gump", id: 13, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Inception", id: 14, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "The Lord of the Rings: The Two Towers",
		id: 15,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{
		name: "One Flew Over the Cuckoo's Nest",
		id: 16,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "Goodfellas", id: 17, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Matrix", id: 18, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Seven Samurai", id: 19, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "Star Wars: Episode IV - A New Hope",
		id: 20,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "City of God", id: 21, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Se7en", id: 22, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Silence of the Lambs", id: 23, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "It's a Wonderful Life", id: 24, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Life Is Beautiful", id: 25, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Usual Suspects", id: 26, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Léon: The Professional", id: 27, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Spirited Away", id: 28, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Saving Private Ryan", id: 29, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Once Upon a Time in the West", id: 30, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "American History X", id: 31, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Interstellar", id: 32, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Casablanca", id: 33, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "City Lights", id: 34, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Psycho", id: 35, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Green Mile", id: 36, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Intouchables", id: 37, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Modern Times", id: 38, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Raiders of the Lost Ark", id: 39, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Rear Window", id: 40, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Pianist", id: 41, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Departed", id: 42, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Terminator 2: Judgment Day", id: 43, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Back to the Future", id: 44, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Whiplash", id: 45, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Gladiator", id: 46, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Memento", id: 47, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Prestige", id: 48, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Lion King", id: 49, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Apocalypse Now", id: 50, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Alien", id: 51, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Sunset Boulevard", id: 52, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
		id: 53,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "The Great Dictator", id: 54, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Cinema Paradiso", id: 55, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Lives of Others", id: 56, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Grave of the Fireflies", id: 57, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Paths of Glory", id: 58, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Django Unchained", id: 59, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Shining", id: 60, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "WALL·E", id: 61, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "American Beauty", id: 62, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Dark Knight Rises", id: 63, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Princess Mononoke", id: 64, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Aliens", id: 65, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Oldboy", id: 66, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Once Upon a Time in America", id: 67, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Witness for the Prosecution", id: 68, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Das Boot", id: 69, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Citizen Kane", id: 70, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "North by Northwest", id: 71, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Vertigo", id: 72, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "Star Wars: Episode VI - Return of the Jedi",
		id: 73,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "Reservoir Dogs", id: 74, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Braveheart", id: 75, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "M", id: 76, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Requiem for a Dream", id: 77, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Amélie", id: 78, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "A Clockwork Orange", id: 79, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Like Stars on Earth", id: 80, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Taxi Driver", id: 81, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Lawrence of Arabia", id: 82, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Double Indemnity", id: 83, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "Eternal Sunshine of the Spotless Mind",
		id: 84,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
	{ name: "Amadeus", id: 1984, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "To Kill a Mockingbird", id: 1962, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Toy Story 3", id: 2010, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Logan", id: 2017, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Full Metal Jacket", id: 1987, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Dangal", id: 2016, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Sting", id: 1973, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "2001: A Space Odyssey", id: 1968, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Singin' in the Rain", id: 1952, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Toy Story", id: 1995, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Bicycle Thieves", id: 1948, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "The Kid", id: 1921, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Inglourious Basterds", id: 2009, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "Snatch", id: 2000, url_logo: "http://somelogo.com/logo.jpeg" },
	{ name: "3 Idiots", id: 2109, url_logo: "http://somelogo.com/logo.jpeg" },
	{
		name: "Monty Python and the Holy Grail",
		id: 1975,
		url_logo: "http://somelogo.com/logo.jpeg",
	},
]
